// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var JSHandle$BsPuppeteer = require("./JSHandle.js");

JSHandle$BsPuppeteer.Impl(/* module */[]);

/*  Not a pure module */
