// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var FrameBase$BsPuppeteer = require("./FrameBase.js");

var makeSelectorOptions = FrameBase$BsPuppeteer.makeSelectorOptions;

exports.makeSelectorOptions = makeSelectorOptions;
/* No side effect */
