// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Util$BsPuppeteer = require("./Util.js");

function makeSelectorOptions(visible, hidden, timeout, _) {
  var tmp = { };
  var tmp$1 = Util$BsPuppeteer.optBoolToJs(visible);
  if (tmp$1) {
    tmp.visible = tmp$1[0];
  }
  var tmp$2 = Util$BsPuppeteer.optBoolToJs(hidden);
  if (tmp$2) {
    tmp.hidden = tmp$2[0];
  }
  if (timeout) {
    tmp.timeout = timeout[0];
  }
  return tmp;
}

exports.makeSelectorOptions = makeSelectorOptions;
/* No side effect */
