// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Puppeteer$BsPuppeteer = require("./Puppeteer.js");

var makeLaunchOptions = Puppeteer$BsPuppeteer.makeLaunchOptions;

exports.makeLaunchOptions = makeLaunchOptions;
/* No side effect */
