// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Js_boolean = require("bs-platform/lib/js/js_boolean.js");
var FrameBase$BsPuppeteer = require("./FrameBase.js");

function setCacheEnabled(enabled, page) {
  return page.setCacheEnabled(Js_boolean.to_js_boolean(enabled));
}

function setJavaScriptEnabled(enabled, page) {
  return page.setJavaScriptEnabled(Js_boolean.to_js_boolean(enabled));
}

function setOfflineMode(enabled, page) {
  return page.setOfflineMode(Js_boolean.to_js_boolean(enabled));
}

function setRequestInterception(enabled, page) {
  return page.setRequestInterception(Js_boolean.to_js_boolean(enabled));
}

var makeSelectorOptions = FrameBase$BsPuppeteer.makeSelectorOptions;

exports.makeSelectorOptions = makeSelectorOptions;
exports.setCacheEnabled = setCacheEnabled;
exports.setJavaScriptEnabled = setJavaScriptEnabled;
exports.setOfflineMode = setOfflineMode;
exports.setRequestInterception = setRequestInterception;
/* No side effect */
