// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Util$BsPuppeteer = require("./Util.js");

function makeConnectOptions(browserWSEndpoint, ignoreHTTPSErrors, _) {
  var tmp = { };
  if (browserWSEndpoint) {
    tmp.browserWSEndpoint = browserWSEndpoint[0];
  }
  var tmp$1 = Util$BsPuppeteer.optBoolToJs(ignoreHTTPSErrors);
  if (tmp$1) {
    tmp.ignoreHTTPSErrors = tmp$1[0];
  }
  return tmp;
}

exports.makeConnectOptions = makeConnectOptions;
/* No side effect */
