// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Util$BsPuppeteer = require("./Util.js");

function makeOptions(path, _type, quality, fullPage, clip, omitBackground, _) {
  var tmp = { };
  if (path) {
    tmp.path = path[0];
  }
  if (_type) {
    tmp.type = _type[0];
  }
  if (quality) {
    tmp.quality = quality[0];
  }
  var tmp$1 = Util$BsPuppeteer.optBoolToJs(fullPage);
  if (tmp$1) {
    tmp.fullPage = tmp$1[0];
  }
  if (clip) {
    tmp.clip = clip[0];
  }
  var tmp$2 = Util$BsPuppeteer.optBoolToJs(omitBackground);
  if (tmp$2) {
    tmp.omitBackground = tmp$2[0];
  }
  return tmp;
}

exports.makeOptions = makeOptions;
/* No side effect */
