// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_boolean = require("bs-platform/lib/js/js_boolean.js");

function optToJs(toJsFn, opt) {
  return Js_option.map(Curry.__1(toJsFn), opt);
}

function optBoolToJs(optBool) {
  return optToJs(Js_boolean.to_js_boolean, optBool);
}

exports.optToJs = optToJs;
exports.optBoolToJs = optBoolToJs;
/* No side effect */
